### ISSUE TITLE
Rapid Tip Shaping Algorithm - Feedback Welcome

### ISSUE THREAD

**Issue by 3DCoded** [3DCoded/3MS#25]
## Introduction

> [!NOTE]
> With the migration to Happy Hare firmware, this feature will become obsolete.

For the past couple of weeks, I have been working on a new method of performing tip shaping. Instead of running in the slicer, this method runs as a Klipper macro. This allows for quickly trying out new settings to see what works best for each of your filaments. 

Before I explain more, I want to give credit where credit is due. The idea for tip shaping in a macro came from [Happy Hare Firmware](https://github.com/moggieuk/Happy-Hare). The basis for this algorithm was originally from [this post](https://www.3dchameleon.com/forum/your-3d-chameleon-creations/20-second-color-changes-on-k1-max) in the 3DChameleon forum. 

So...how is it better than standard tip shaping? 

- **Faster:** In my testing, this method is around 1.5-2.5x faster than standard tip shaping, resulting in ~20s color swaps
- **Easier Tuning:** As I mentioned earlier, this method allows for testing your tip shaping with a simple macro
- **More Reliable:** In my testing, this method has proved **significantly** more reliable than standard tip shaping. This is likely because tuning tips with traditional tip shaping is a long process, so I settled for decent tips, not near-perfect ones. With this method, I kept tuning until my tips looked nearly perfect.

## Filament Cutters

Before we go further, if you can install a mechanical filament cutter on your printer below your filament sensor (closer to the nozzle), please do that! Filament cutters are much, **much** faster and more reliable than tip shaping will ever be, and there's no tuning required. 

Thank you @ImChrono for implementing this! The documentation is available [here](https://3dcoded.github.io/3MS/guides/manualcutter/).

## How it Works

If you aren't using a filament cutter, back to tip shaping. This algorithm uses only **four** G-Code moves. That means that while there are less things to tune, each setting can have a big impact on your filament tips.

I've broken them down below:

1. Quickly push the filament out of the nozzle
    - This is essentially the ramming stage of standard tip shaping
    - This part actually forms the tip of the filament
    - This leaves a string of filament on the nozzle that is meant to be "caught" by the wipe tower (explained more later)
2. Quickly retract the filament to the cooling tube
    - Tuning this speed is **crucial** to keeping the filament tip shape through the next step
3. Slowly retract the filament through the cooling tube
    - This is similar to the cooling moves performed by standard tip shaping, however it doesn't move the filament back and forth
    - This step controls how flat/sharp/stringy the filament tip is
    - This also controls how molten the filament tip is when it exits the extruder
4. Quickly retract the filament out of the extruder
    - This step isn't too important to tune if the previous three steps were done right

## Documentation

Documentation for rapid tip shaping is available [here](https://3dcoded.github.io/3MS/experimental/rapidtip/). 

TODO's for rapid tip shaping:

- [ ] IN PROGRESS: Support for custom `PARK` and `UNPARK` macros
- [ ] Any feedback given here

TODO's for the documentation:

- [x] Slicer setup
- [ ] Pictures of filament tips
- [ ] Any feedback given here

## Feedback

Please feel free to give any feedback on this feature. This is still in development, so expect frequent changes.

**Comment by bsafh** [comment]
"Thank you @ImChrono for implementing this! The documentation is available [here](https://3dcoded.github.io/3MS/guides/manualcutter/)."

Which cutter can be used and how to connect it to the controller ???

**Comment by 3DCoded** [comment]
Any filament cutter that cuts below the filament sensor can be used. It is controlled by a mechanical switch that the printhead pushes against the frame/gantry of the printer to cut the filament.

**Comment by bsafh** [comment]
Ok ... limit still a bit lost how to find one, but well ...

**Comment by 3DCoded** [comment]
What printer are you using? There are a some pre-designed filament cutters for certains printers (e.g. Filametrix cutter for Voron printers)

**Comment by bsafh** [comment]
for this direct drive extruder: https://www.tronxy3d.com/de/products/tronxy-3d-printer-parts-high-temperature-print-head-for-x5sa-series?variant=43828171833588 (320°C version) and this Klipper control unit https://www.tronxy3d.com/products/tronxy-klipper-firmware-upgrade-kits?variant=44680278671604 - it's a Tronxy 5XSA Pro printer

**Comment by bsafh** [comment]
Two printer, but only one with Klipper ...

1) Geeetech A30 (not Klipper)

2) Tronxy X5SA Pro, but with the Klipper Update Kit and an direct drive
extruder/hotend update kit:

for this direct drive extruder:
https://www.tronxy3d.com/de/products/tronxy-3d-printer-parts-high-temperature-print-head-for-x5sa-series?variant=43828171833588
(320°C
version) and this Klipper control unit
https://www.tronxy3d.com/products/tronxy-klipper-firmware-upgrade-kits?variant=44680278671604
-
it's a Tronxy 5XSA Pro printer


Regards


Christian B.


Christopher Mattar ***@***.***> schrieb am Do., 7. Nov. 2024,
22:41:

**Comment by ImChrono** [comment]
I also suggest opening a new issue so that this thread can stay focused on tip shaping suggestions and improvements

**Comment by bsafh** [comment]
> I also suggest opening a new issue so that this thread can stay focused on tip shaping suggestions and improvements

https://github.com/3DCoded/3MS/issues/27#issue-2644777164

**Comment by 3DCoded** [comment]
> As a side note, I'm planning to release a second PR soon, which will include filament retraction between swaps to save filament, as well as support for a servo cutter.

Before you spend too much time working your PR, the beta of Happy Hare v3 (which supports the 3MS) should be released very soon. All the existing 3MS macros will be archived after the final release of Happy Hare, including contributed code.

**Comment by ImChrono** [comment]
That's great news! As you pointed out, Happy Hare is a solid alternative. Once TYPE B MMU gains full compatibility, I'll switch my new setup to that firmware as well.

**Comment by bsafh** [comment]
🙂🙃

I'll see. Still new to Klipper...

**Comment by 3DCoded** [comment]
> 🙂🙃
> 
> I'll see. Still new to Klipper...

[This](https://klipper.discourse.group/t/macro-creation-tutorial/30) is a really good guide for writing Klipper macros.

**Comment by 3DCoded** [comment]
Closing as the 3MS is now fully migrated to HH
