### ISSUE TITLE
[FR]: filament cutter (servo driven)

### ISSUE THREAD

**Issue by bsafh** [3DCoded/3MS#26]
I also have a Tronxy X5SA (not Pro) but modified the gantry with a custom setup using linear motion instead of rollers. Unfortunately, I don’t have the same print head, so I can’t help with designing a custom mechanical cutter. However, you could try remixing this model:
[Small Filament Cutter](https://www.printables.com/model/793488-small-filament-cutter/files).

I think there should be enough space to place the cutter between the extruder and the hotend

As a side note, I'm planning to release a second PR soon, which will include filament retraction between swaps to save filament, as well as support for a servo cutter.

I think a servo cutter might be an easier option for your printer since it would minimize the need to move the printhead, which looks a bit heavy...

_Originally posted by @ImChrono in https://github.com/3DCoded/3MS/issues/25#issuecomment-2464252630_

**Comment by bsafh** [comment]
sorry, duplicate

**Comment by 3DCoded** [comment]
I'll close this duplicate.
