### ISSUE TITLE
[Bug]: Unknown Pin Chip Name '3ms'

### ISSUE THREAD

**Issue by brentdeacon23** [3DCoded/3MS#39]
### What happened?

I am on the SKR Mini V2. the line in mmu.cfg in the specific file for that board, the line [static_digital_output usb_pullup_enable]
pins: !3ms: PA14 thows an Unknown pin chip name '3ms' on the k1

### Klippy Log

[klippy.log](https://github.com/user-attachments/files/18087769/klippy.log)

**Comment by 3DCoded** [comment]
Hi @brentdeacon23 ,

Thank you for finding this bug. I have updated the `mmu.cfg` for the SKR Mini with a fix. After re-installing the file, the error should no longer be present.

**Comment by brentdeacon23** [comment]
Do you need to flash klipper from the K1 itself or can you use a rasberry pi with klipper installed?

**Comment by 3DCoded** [comment]
@brentdeacon23 

You can use an external Raspberry Pi with Klipper to flash the SKR.
