### ISSUE TITLE
[MCU]: MKS Monster8

### ISSUE THREAD

**Issue by Mawe066** [3DCoded/3MS#40]
### What kind of controller is this?

main MCU (using spare stepper ports on existing MCU)

### Controller name

MKS Monster8

### More information

For the usage in Happy Hare with no exra MCU. All Steppers are inside the existing MCU

**Comment by 3DCoded** [comment]
Hi @Mawe066 ,

Do you want the last 4 ports to be used for 3MS extruders (E1, E2, E3, and E4)?

**Comment by Mawe066** [comment]
Yes, I have an direct drive and 4 feeding extruders

**Comment by 3DCoded** [comment]
Hello @Mawe066 ,

I have created the configs using the new configuration generator tool (docs coming soon). Here are the configuration files:

[mmu.zip](https://github.com/user-attachments/files/18117653/mmu.zip)

**Comment by Mawe066** [comment]
that was quick, thank you!

**Comment by 3DCoded** [comment]
Hi @Mawe066 ,

I have found an error in the `mmu_hardware.cfg` I generated. Here's the updated one:

[mmu_hardware.cfg.zip](https://github.com/user-attachments/files/18126428/mmu_hardware.cfg.zip)

**Comment by Mawe066** [comment]
What was that error? Maybe I already fixed it. I needed a few more parameters to get no errors.

**Comment by Mawe066** [comment]
![Screenshot_2024-12-13-14-04-03-243_com android chrome](https://github.com/user-attachments/assets/dabbfb6b-9fd4-43ee-84fb-76a6782b60f7)

Got errors in missing parameters on interpolate and sense resistor. Had to add these

**Comment by Mawe066** [comment]
Ah and I forgot to mention, I use 2209 steppers. In your config were 2208. Maybe add a question in the request template for this

**Comment by 3DCoded** [comment]
Good idea. I've updated the form so future requests will include the driver question.
