### ISSUE TITLE
[MCU]: Add Bigtreetech SKR V1.3

### ISSUE THREAD

**Issue by Marcin1415** [3DCoded/3MS#41]
### What kind of controller is this?

extra MCU (MCU used specifically for the 3MS)

### Controller name

BTT SKR V1.3

### Stepper Driver Type

A4988

### More information

12/24V

**Comment by 3DCoded** [comment]
Hello @Marcin1415 ,

I have created a config for the BTT SKR v1.3:

[skr13.zip](https://github.com/user-attachments/files/18135610/skr13.zip)
