### ISSUE TITLE
[MCU]: Spider V3 

### ISSUE THREAD

**Issue by Gabriel121217** [3DCoded/3MS#42]
### What kind of controller is this?

main MCU (using spare stepper ports on existing MCU)

### Controller name

Fysetc Spider V3

### Stepper Driver Type

TMC2209

### More information

24V power supply
Intended to set up 2 channel MMU

**Comment by 3DCoded** [comment]
Hi @Gabriel121217 ,

Which motors do you want to be used as 3MS motors?

- X-MOT
- Y-MOT
- Z-MOT
- E1-MOT
- E2-MOT
- E3-MOT

**Comment by Gabriel121217** [comment]
Hey, I am using E0 & E3

**Comment by 3DCoded** [comment]
Hi @Gabriel121217 ,

Here are the configs:

[spider.zip](https://github.com/user-attachments/files/18150762/spider.zip)

**Comment by Gabriel121217** [comment]
Thank you so much!
