### ISSUE TITLE
[Bug]: SKR Mini e3 V2 mmu.cfg 

### ISSUE THREAD

**Issue by brentdeacon23** [3DCoded/3MS#43]
### What happened?

Trying to run on K1. Error thrown, seems to be related to happy-hare/configurations/MMU_0_3_btt_skr_mini_e3_v2/mmu.cfg 

Error:
pin MMU_GEAR_UART_1 is an alias for MMU_GEAR_UART

### Klippy Log

[klippy.log](https://github.com/user-attachments/files/18204622/klippy.log)

**Comment by 3DCoded** [comment]
Hello @brentdeacon23 ,

I have found the issue in the configuration and fixed it. Please let me know if this works.
